// Code generated by protoc-gen-go.
// source: memory.proto
// DO NOT EDIT!

/*
Package memory is a generated protocol buffer package.

It is generated from these files:
	memory.proto

It has these top-level messages:
	SearchRequest
	SearchReply
*/
package memory

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SearchRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *SearchRequest) Reset()                    { *m = SearchRequest{} }
func (m *SearchRequest) String() string            { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()               {}
func (*SearchRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SearchRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type SearchReply struct {
	Memory string `protobuf:"bytes,2,opt,name=memory" json:"memory,omitempty"`
}

func (m *SearchReply) Reset()                    { *m = SearchReply{} }
func (m *SearchReply) String() string            { return proto.CompactTextString(m) }
func (*SearchReply) ProtoMessage()               {}
func (*SearchReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SearchReply) GetMemory() string {
	if m != nil {
		return m.Memory
	}
	return ""
}

func init() {
	proto.RegisterType((*SearchRequest)(nil), "memory.SearchRequest")
	proto.RegisterType((*SearchReply)(nil), "memory.SearchReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for MemorySearcher service

type MemorySearcherClient interface {
	SearchMemory(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchReply, error)
}

type memorySearcherClient struct {
	cc *grpc.ClientConn
}

func NewMemorySearcherClient(cc *grpc.ClientConn) MemorySearcherClient {
	return &memorySearcherClient{cc}
}

func (c *memorySearcherClient) SearchMemory(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchReply, error) {
	out := new(SearchReply)
	err := grpc.Invoke(ctx, "/memory.MemorySearcher/SearchMemory", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for MemorySearcher service

type MemorySearcherServer interface {
	SearchMemory(context.Context, *SearchRequest) (*SearchReply, error)
}

func RegisterMemorySearcherServer(s *grpc.Server, srv MemorySearcherServer) {
	s.RegisterService(&_MemorySearcher_serviceDesc, srv)
}

func _MemorySearcher_SearchMemory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemorySearcherServer).SearchMemory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/memory.MemorySearcher/SearchMemory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemorySearcherServer).SearchMemory(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MemorySearcher_serviceDesc = grpc.ServiceDesc{
	ServiceName: "memory.MemorySearcher",
	HandlerType: (*MemorySearcherServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SearchMemory",
			Handler:    _MemorySearcher_SearchMemory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "memory.proto",
}

func init() { proto.RegisterFile("memory.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 167 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0xc9, 0x4d, 0xcd, 0xcd,
	0x2f, 0xaa, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x83, 0xf0, 0x94, 0x94, 0xb9, 0x78,
	0x83, 0x53, 0x13, 0x8b, 0x92, 0x33, 0x82, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0x84, 0xb8,
	0x58, 0xf2, 0x12, 0x73, 0x53, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0xc0, 0x6c, 0x25, 0x55,
	0x2e, 0x6e, 0x98, 0xa2, 0x82, 0x9c, 0x4a, 0x21, 0x31, 0x2e, 0xa8, 0x6e, 0x09, 0x26, 0xb0, 0x22,
	0x28, 0xcf, 0xc8, 0x8f, 0x8b, 0xcf, 0x17, 0xcc, 0x82, 0x28, 0x4e, 0x2d, 0x12, 0xb2, 0xe1, 0xe2,
	0x81, 0xb0, 0x21, 0xe2, 0x42, 0xa2, 0x7a, 0x50, 0x47, 0xa0, 0xd8, 0x29, 0x25, 0x8c, 0x2e, 0x5c,
	0x90, 0x53, 0xa9, 0xc4, 0xe0, 0xa4, 0xc1, 0x25, 0x9e, 0x99, 0xaf, 0x97, 0x5e, 0x54, 0x90, 0xac,
	0x97, 0x5a, 0x91, 0x98, 0x5b, 0x90, 0x93, 0x5a, 0x0c, 0x55, 0xe8, 0xc4, 0x0d, 0x31, 0x30, 0x00,
	0xe4, 0x97, 0x00, 0xc6, 0x24, 0x36, 0xb0, 0xa7, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0xe6,
	0x5e, 0xbc, 0x44, 0xe4, 0x00, 0x00, 0x00,
}
